### ISSUE TITLE
Not the same with the the command used in bazel

### ISSUE THREAD

**Issue by ChunyangLee** [grailbio/bazel-compilation-database#108]
Hi， I am new to bazel.
I find that the generated command in compile_commands.json is not the same as the one bazel actually uses.

For example, 
**The one bazel uses:**
 /usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/test/test_compilation_db/_objs/hello-world/hello-world.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/test/test_compilation_db/_objs/hello-world/hello-world.pic.o' -fPIC -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/bin/external/bazel_tools -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c test/test_compilation_db/hello-world.cc -o bazel-out/k8-fastbuild/bin/test/test_compilation_db/_objs/hello-world/hello-world.pic.o)

**The generated one in compile_commands.json:**
[{"command":"/usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -std=c++0x -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/bin/external/bazel_tools -x c++ -c test/test_compilation_db/hello-world.cc","directory":"__EXEC_ROOT__","file":"test/test_compilation_db/hello-world.cc"},{"command":"/usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -std=c++0x -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/bin/external/bazel_tools -x c++ -c test/test_compilation_db/hello-time.h","directory":"__EXEC_ROOT__","file":"test/test_compilation_db/hello-time.h"},{"command":"/usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -std=c++0x -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -iquote . -iquote bazel-out/k8-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/bin/external/bazel_tools -x c++ -c bazel-out/k8-fastbuild/bin/test/test_compilation_db/libhello-time.so","directory":"__EXEC_ROOT__","file":"bazel-out/k8-fastbuild/bin/test/test_compilation_db/libhello-time.so"}]

In compile_commands.json, the -o part is missed, and the MD, -frandom parts are also missed.

While, I am new to bazel, may I ask?
Does the bazel offer the method to access these missed parts?  Would you please teach me how to add these ?

**Comment by siddharthab** [comment]
This project is being archived.
