### ISSUE TITLE
aspects option cannot recognize the relative path of "aspects.bzl"

### ISSUE THREAD

**Issue by tomcruiseqi** [grailbio/bazel-compilation-database#11]
Hello:

These are my steps using bazel-compilation-database in VIM:
1. Install YCM with Vundle.
2. Clone this repository and set let g:ycm_global_ycm_extra_conf='PATH TO .ycm_extra_conf.py
3. Change directory to tests and vim a.cc
4. OK to run .ycm_extra_conf.py
5. And there are errors: 
CalledProcessError: Command '['bazel', 'build', '--aspects=../aspects.bzl%compilation_database_aspect', '--output_groups=compdb_files', u'//:A']' returned non-zero exit status 1

bazel version: 0.16.0

Thanks

**Comment by tomcruiseqi** [comment]
Thanks for your intermediate response.

No. I didn't clone this repository inside my bazel workspace because of the YCM's ycm_global_ycm_extra_conf option. I used the tests inside this repository and the error always appears. I think  it is that --aspects option of bazel doesn't support file path causes this problem. So I remove the ycm_global_ycm_extra_conf option in my vimrc file and copy the aspects.bzl and .ycm_extra_conf.py to the directory of my bazel workspace.  And it works!

But this solution causes another problem.  I need to copy these two files to every directory of bazel workspace.  Is there an easy and convenient solution for this?

Thanks!

**Comment by siddharthab** [comment]
You don't need to copy them everywhere. The way I have it is like this:
```
WORKSPACE 
.ycm_extra_conf.py (symlink) -> .compdb/ycm_extra_conf.py
 |
 -> .compdb
      |
       -> .ycm_extra_conf.py 
       -> aspects.bzl
```

**Comment by tomcruiseqi** [comment]
Yes, there should be a aspects.bzl in the workspace. And the .ycm_extra_conf.py can be a symbolic link to the file of this repository.
