### ISSUE TITLE
ERROR: error loading package 'bazel-compilation-database/tests': Extension file not found. Unable to load package for '@compdb//:aspects.bzl': The repository could not be resolved

### ISSUE THREAD

**Issue by xiedeacc** [grailbio/bazel-compilation-database#13]
➜  hello-server git:(master) ✗ git clone git@github.com:grailbio/bazel-compilation-database.git
Cloning into 'bazel-compilation-database'...
remote: Enumerating objects: 89, done.
remote: Total 89 (delta 0), reused 0 (delta 0), pack-reused 89
Receiving objects: 100% (89/89), 24.38 KiB | 4.88 MiB/s, done.
Resolving deltas: 100% (47/47), done.
➜  hello-server git:(master) ✗ ls
bazel-bin  bazel-compilation-database  bazel-genfiles  bazel-hello-server  bazel-out  bazel-testlogs  BUILD  CPPLINT.cfg  src  tags  tools  WORKSPACE
➜  hello-server git:(master) ✗ ./bazel-compilation-database/generate.sh 
ERROR: error loading package 'bazel-compilation-database/tests': Extension file not found. Unable to load package for '@compdb//:aspects.bzl': The repository could not be resolved
INFO: Analysed 0 targets (0 packages loaded).
INFO: Found 0 targets...
INFO: Elapsed time: 0.719s, Critical Path: 0.00s
INFO: 0 processes.
➜  hello-server git:(master) ✗

**Comment by siddharthab** [comment]
`git clone` will not work because it will also copy the tests directory which will not work.

The instructions given in the README will work for you. Which suggests to directly download a release archive. These archives exclude the tests directory through the .gitattributes file.

Please close the issue if it works for you.

**Comment by xiedeacc** [comment]
thanks, I download a release archive, then appear another problem
ERROR: Invalid aspect './aspects.bzl%compilation_database_aspect': Invalid label: invalid package name '.': package name component contains only '.' characters: Invalid label: invalid package name '.': package name component contains only '.' characters
INFO: Elapsed time: 0.233s
INFO: 0 processes.

**Comment by xiedeacc** [comment]
> `git clone` will not work because it will also copy the tests directory which will not work.
> 
> The instructions given in the README will work for you. Which suggests to directly download a release archive. These archives exclude the tests directory through the .gitattributes file.
> 
> Please close the issue if it works for you.

I have a test demo on github ,do you need it ?

**Comment by xiedeacc** [comment]
fix it by add a build rule to BUILD

**Comment by Abbyyan** [comment]
> fix it by add a build rule to BUILD
Sorry to bother you . I have got the same problem , could you describe  the solve method in more detail please？ Thanks a lot.

**Comment by Abbyyan** [comment]
> fix it by add a build rule to BUILD

Sorry to bother you . I have got the same problem , could you describe the solve method in more detail please？ Thanks a lot.

**Comment by siddharthab** [comment]
Hello @Abbyyan, can you tell me how are you using the project? Are you using the generate.sh script, the YouCompleteMe python file, or the bazel build rule?
