### ISSUE TITLE
doesn't have provider 'cc' error with bazel-0.25.0

### ISSUE THREAD

**Issue by soonho-tri** [grailbio/bazel-compilation-database#25]
https://github.com/grailbio/bazel-compilation-database/blob/d6420382e62780904159338d7d8293c7b0e8528e/aspects.bzl#L128-L130

It's from the line 129, `target.cc.compile_flags`, which is now deprecated (from bazel-0.25.0). Please see https://github.com/bazelbuild/bazel/issues/7036 for details. I think a solution is to use `get_compile_flags(target)` instead of `target.cc.compile_flags`. AFAIK, `get_compile_flags` is not included in bazel so we need to copy/paste it from https://gist.github.com/oquenchil/7e2c2bd761aa1341b458cc25608da50c.

**Comment by siddharthab** [comment]
Thank you for the report. I will most likely look at all bazel 0.25 compatibility issues in the coming weekend.

**Comment by siddharthab** [comment]
This is now fixed through 4a1469a3a9720c13ff9f5abeef1d710a826c2f1c and included in release 0.3.4.

Thank you for your patience.

**Comment by soonho-tri** [comment]
@siddharthab , thank you!
