### ISSUE TITLE
Does not work with Bazel 0.27.0

### ISSUE THREAD

**Issue by grant-rez** [grailbio/bazel-compilation-database#31]
Hi,

I'm new to Bazel and am trying to set up my environment (specifically in vim) and thought that this project would be very useful. It seems though that the project is not compatible with bazel 0.27.0. 

I tried all three methods outlined in the readme, but could not get any of them working. I have a very basic build file so I don't think that is the problem. I tried troubleshooting by manually editing aspects.bzl and adding ctx=ctx in the cc_common.configure_features but that led me to further problems. 

I was able to build my project with no errors using this command `bazel build --noincompatible_depset_is_not_iterable --noincompatible_depset_union '...'` but the compile_commands.json file it produced had empty square brackets only. 

Thanks for putting all the work into this project that you have, I'm excited to use it!

**Comment by siddharthab** [comment]
A new version 0.3.5 haas been released that will work with bazel 0.27. Thanks to #30.
