### ISSUE TITLE
Error: name 'CcInfo' is not defined

### ISSUE THREAD

**Issue by jedichen121** [grailbio/bazel-compilation-database#35]
I'm trying to generate a compilation database for google's bazel tutorial. However, I got the following error using 0.3.5. 

```
ERROR: /home/jedi/bazel_examples/cpp-tutorial/stage1/bazel-compilation-database-0.3.5/aspects.bzl:88:31: name 'CcInfo' is not defined
ERROR: Extension 'bazel-compilation-database-0.3.5/aspects.bzl' has errors
ERROR: Analysis of aspect '//bazel-compilation-database-0.3.5:aspects.bzl%compilation_database_aspect of //main:hello-world' failed; build aborted: Extension 'bazel-compilation-database-0.3.5/aspects.bzl' has errors
```

I'm wondering which bazel version this tool support. I'm using bazel 0.18.0. Is this too old? Thank you for any help.

**Comment by siddharthab** [comment]
Yes, 0.18 is too old. I am not maintaining a compatibility table for all versions of bazel, but I can guarantee that this project works for bazel versions 0.27 and higher.

**Comment by jedichen121** [comment]
Using 0.27.2 did work. 

Btw, do you know if the generated compilation database is compatible with [scan-build](https://github.com/rizsotto/scan-build)? I'm trying to use it to do static analysis but the tool failed on the database.

**Comment by siddharthab** [comment]
I have not tested it, but should be. The output file follows the [specs](https://clang.llvm.org/docs/JSONCompilationDatabase.html).
