### ISSUE TITLE
files are relative to bazel-out

### ISSUE THREAD

**Issue by oliverdain** [grailbio/bazel-compilation-database#40]
If I run `generate.sh` I get a valid `compile_commands.json` but all the include paths are relative to the sandbox. For example,  the compile line includes:

```
-I bazel-out/darwin-fastbuild/bin/cpp/utils/math/_virtual_includes/math
```

As a result, if I jump to symbol definitions in vim (or any other editor) I jump to the file in the sandbox instead of to the actual source file. This makes it difficult to navigate around my own code. I tried adding `--spawn_strategy=local` to the `bazel` command in `generate.sh` but that didn't help. Obviously I can run `sed` or something on the generated compile commands to fix the paths but it seems like that shouldn't be necessary. Wouldn't most users want the paths to be to their own source code rather than paths in the sandbox?

**Comment by siddharthab** [comment]
I apologize for my prolonged absence, and I thank you for taking the time to report an issue.

Are you running with `sandbox_strategy=standalone` or some other flags like that? I ask because I see that you are jumping to a `_virtual_includes` file which are special cases (see #29), and will be available to you only when running in non-"sandbox" strategies.

For all other cases, the file to which you will jump will belong to a symlink farm pointing to your original source files. It usually works well, and vim (YCM) follows the symlink to the original source file when jumping. I tested this just now with the abseil-cpp project. If it is not working for you, can you give me a dummy project and the bazel flags you are using to reproduce the issue please?

**Comment by ak-ambi** [comment]
Hello @siddharthab. My issue is that I am not using YCM, but vscode editor with clangd plugin. This tool won't use python code dedicated to point YCM to the correct files.

**Comment by siddharthab** [comment]
What I am describing should work with any editor because the file within the execroot path is just a symlink to the original file. Is that not the case in your setup?

There is no special handling of file paths in the python code for YCM.

**Comment by siddharthab** [comment]
I am just trying to understand what I am missing here. Using the exec_root is the cleanest way. Directly using the source directory will have more corner cases to manage.

**Comment by oliverdain** [comment]
Yes, if I jump to the symbol it does take me to the symlinked file. But then I often do things like `Ex` or use other custom commands I have to jump from one file to another bases on the directory of my current file and that gets confusing. I can end up with 2 copies of the same file opened in vim because I got to one of them by opening the file from it's original location and/or using a macro like "find the .cpp that goes with this .h" and then a 2nd instance of the same file opened via the symlink so it can get really confusing. And yes, I am doing `strip_include_prefix` which further complicates matters.

**Comment by siddharthab** [comment]
Thank you. I think I understand. For both vscode and your vim settings, your path is not followed to the realpath of the file. For my vim at least, when I jump, I am taken to the original directory.

I can put this feature behind a flag, because I think this may lead to more corner cases for clang because we now have to symlink all relevant directories in execroot to the repo directory for clang to be able to find all the files from external repos, and generated files.

**Comment by oliverdain** [comment]
@siddharthab I'd been using a different mechanism to generate compiler commands but just came back to this. I built a `compile_commands.json` using the 0.4.5 release and the issue persists. For example, here's one of the lines that were in my `compile_commands.json` generated via `bazel-compdb -s`:

```
{"command":"/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g -std=c++0x -std=c++14 -fno-canonical-system-headers -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -isystem external/tp2-linux-dbg-v008/glog/include -isystem bazel-out/k8-dbg/bin/external/tp2-linux-dbg-v008/glog/include -isystem external/tp2-linux-dbg-v008/boost/include -isystem bazel-out/k8-dbg/bin/external/tp2-linux-dbg-v008/boost/include -isystem external/tp2-linux-dbg-v008/ranges/include -isystem bazel-out/k8-dbg/bin/external/tp2-linux-dbg-v008/ranges/include -isystem external/tp2-linux-dbg-v008/yaml_cpp/include -isystem bazel-out/k8-dbg/bin/external/tp2-linux-dbg-v008/yaml_cpp/include -I bazel-out/k8-dbg/bin/cpp/utils/serialize/_virtual_includes/serialize -I bazel-out/k8-dbg/bin/cpp/utils/logging/_virtual_includes/logging -I bazel-out/k8-dbg/bin/cpp/utils/logging/_virtual_includes/logging_private_headers -I bazel-out/k8-dbg/bin/cpp/utils/common/_virtual_includes/common -I bazel-out/k8-dbg/bin/cpp/utils/exception/_virtual_includes/exception -I bazel-out/k8-dbg/bin/cpp/utils/exception/_virtual_includes/exception_private_headers -I bazel-out/k8-dbg/bin/cpp/utils/common/_virtual_includes/common_private_headers -I bazel-out/k8-dbg/bin/cpp/utils/serialize/_virtual_includes/serialize_private_headers -iquote . -iquote bazel-out/k8-dbg/bin -iquote external/tp2-linux-dbg-v008 -iquote bazel-out/k8-dbg/bin/external/tp2-linux-dbg-v008 -march=broadwell -Wno-sign-compare -Wno-unknown-pragmas -Werror -I /usr/lib/gcc/x86_64-linux-gnu/8/include -I /usr/local/include -I /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I /usr/include/x86_64-linux-gnu -I /usr/include -I /usr/include/c++/8 -I /usr/include/x86_64-linux-gnu/c++/8 -I /usr/include/c++/8/backward -x c++ -c cpp/utils/serialize/include/utils/serialize/input.h","directory":"/home/oliver/Documents/code/revl","file":"cpp/utils/serialize/include/utils/serialize/input.h"},
```

Note all the `-I` flags with `bazel-out/k8-dbg/bin/<path>/_virtual_includes` in them. Shouldn't the `-s` flag to `bazel-compdb` have caused those to be paths to the actual files instead of their bazel-out variants?

**Comment by oliverdain** [comment]
BTW: I don't have permissions to re-open this issue but I'm hoping given the output above you will re-open it. Thanks.
