### ISSUE TITLE
Distribute with EasyClangComplete

### ISSUE THREAD

**Issue by niosus** [grailbio/bazel-compilation-database#43]
Hey guys! First of all, thanks so much for this! Using your tool on a daily basis and it makes my life enormously easier! 

This is not an issue, just a question. I am maintaining a clang-based completion plugin for Sublime Text 3: [EasyClangComplete](https://github.com/niosus/EasyClangComplete) and your tool looks like a perfect match for it. For now I am able to generate compilation database when using CMake out of the box while there is still a need for a manual step in case of bazel. 

So the question is: would you be fine if I distribute your tool alongside my plugin in some way? Currently, I would probably just clone your project whenever my plugin starts. 

Would love to hear your thoughts on this! Thanks again!

**Comment by siddharthab** [comment]
I apologize for my prolonged absence.

Sure thing. You are more than welcome to copy and distribute the source code or any derivatives. The license allows it. Just be sure to keep the license headers in your copy of the source code.

Thank you for your interest and support.

**Comment by niosus** [comment]
Just a heads up. Your script is now integrated as a command into [EasyClangComplete](https://github.com/niosus/EasyClangComplete) :wink: 

Thanks so much for your efforts!
