### ISSUE TITLE
README.md instructions need an update

### ISSUE THREAD

**Issue by mapx** [grailbio/bazel-compilation-database#5]
I follow the first way in [How to Use](https://github.com/grailbio/bazel-compilation-database#how-to-use). In a bazel-cleaned repo, it outputs:
```bash
INFO: Loading package: @bazel_tools//tools/cpp
INFO: Loading package: @local_config_cc//
find: ‘/home/user/.cache/bazel/_bazel_user/67c1fe002917e3ed20bcd24da34a010d/execroot/the_repo’: No such file or directory
```
After running a bazel command like `bazel build //:some_target`, I retry `bazel-compdb/generate.sh`. It outputs:
```bash
ERROR: error loading package 'bazel-compdb/tests': Extension file not found. Unable to load package for '@compdb//:aspects.bzl': The repository could not be resolved.
ERROR: error loading package 'bazel-compdb/tests': Extension file not found. Unable to load package for '@compdb//:aspects.bzl': The repository could not be resolved.
```
`compile_commands.json` is then created with an empty array as its content.

Thanks.

**Comment by siddharthab** [comment]
Thank you for reporting this error. This seems to have been introduced by my latest commit. I will send in a fix soon.

**Comment by siddharthab** [comment]
I have updated the instructions in the latest commit (c56fc3b11cee27a3e97ec3c1d01fff05c76d16a7). This should work out of the box now. Please reopen this issue if it does not.
