### ISSUE TITLE
Failed to generate

### ISSUE THREAD

**Issue by 372046933** [grailbio/bazel-compilation-database#54]
```
ERROR: /home/tx/Downloads/github/tensorflow/third_party/ortools/BUILD.bazel:7:1: name 'native' is not defined
ERROR: package contains errors: third_party/ortools
ERROR: error loading package 'third_party/toolchains/embedded/arm-linux': Unable to load file '//third_party/toolchains/embedded/arm-linux:cc_config.bzl': file doesn't exist

```

**Comment by siddharthab** [comment]
Are you using this project on the tensorflow repo?

**Comment by 372046933** [comment]
yes

**Comment by siddharthab** [comment]
Hi! So, the entire tensorflow project is difficult to query or build, and does not work out of the box. We will have better luck if we focus on just [selected targets](https://github.com/grailbio/bazel-compilation-database#selected-targets) in the repo. For example, the target `//tensorflow:libtensorflow_framework.so.2.2.0` works for me, and you can add any more that you are directly working on.

```
load("@com_grail_bazel_compdb//:aspects.bzl", "compilation_database")

compilation_database(
    name = "compdb",
    targets = [
        "//tensorflow:libtensorflow_framework.so.2.2.0",
    ],
)
```

**Comment by 372046933** [comment]
Thanks for your help. But I just got the same error :(

**Comment by siddharthab** [comment]
Hello.

I updated the instructions in the [README](https://github.com/grailbio/bazel-compilation-database#selected-targets) for your use case. Please take a look and see if you still have problems.

I am going to close the issue for now. Please reopen if you still can not get it to work.
