### ISSUE TITLE
Missing -MD -MF

### ISSUE THREAD

**Issue by HackAttack** [grailbio/bazel-compilation-database#63]
The autogenerated toolchain definiton for both gcc and clang on Linux (Ubuntu 20.04) produces

```
-MD -MF bazel-out/k8-fastbuild/bin/_objs/main/main.pic.d
```

as part of the command when building

```bazel
cc_binary(
    name = "main",
    srcs = ["main.cpp"],
)
```

but this is not reflected in the compilation database.

Relevant section of `$(bazel info execution_root)/external/local_config_cc/cc_toolchain_config.bzl`:

```starlark
dependency_file_feature = feature(
    name = "dependency_file",
    enabled = True,
    flag_sets = [
        flag_set(
            actions = [
                ACTION_NAMES.assemble,
                ACTION_NAMES.preprocess_assemble,
                ACTION_NAMES.c_compile,
                ACTION_NAMES.cpp_compile,
                ACTION_NAMES.cpp_module_compile,
                ACTION_NAMES.objc_compile,
                ACTION_NAMES.objcpp_compile,
                ACTION_NAMES.cpp_header_parsing,
                ACTION_NAMES.clif_match,
            ],
            flag_groups = [
                flag_group(
                    flags = ["-MD", "-MF", "%{dependency_file}"],
                    expand_if_available = "dependency_file",
                ),
            ],
        ),
    ],
)
```

I’m not sure if there is a use case for which this is actually important, but I thought I’d report it since it’s a discrepancy between what was actually executed and what the compilation database claims the command was.

**Comment by siddharthab** [comment]
Thanks for the report. There have been many changes to the C++ toolchain since this project was initially written, and I have mainly relied on community support. So thank you for your efforts.

I am actually looking to transfer the ownership of this project to someone who is interested. Will you be willing to take over?

**Comment by HackAttack** [comment]
I’m not sure I can commit to full ownership but if you want to promote me to collaborator I can try to help out.

**Comment by siddharthab** [comment]
Thanks. I just sent you an invite for Write access.

**Comment by siddharthab** [comment]
I think it's perhaps desirable to skip these flags. The -MD and -MF flags tell the compiler to effectively write a Makefile for this compile action at the location given by -MF. Even if we do include this flag, we would want to keep a different temporary location for -MF.

Let's close the issue until a valid use case comes up which can guide us on how to do this properly.
