### ISSUE TITLE
[DOC]: More detailed Documentation on selected-targets.

### ISSUE THREAD

**Issue by shipleyxie** [grailbio/bazel-compilation-database#69]
I want to use your repo in TensorFlow source project , following the instruction [selected-targets](https://github.com/grailbio/bazel-compilation-database#selected-targets), But got some ERROR like this:
```
Starting local Bazel server and connecting to it...
ERROR: Skipping '//tensorflow:example_compdb': error loading package 'tensorflow': Encountered error while reading extension file 'aspects.bzl': no such package '@com_grail_bazel_compdb//': java.io.IOException: thread interrupted
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow': Encountered error while reading extension file 'aspects.bzl': no such package '@com_grail_bazel_compdb//': java.io.IOException: thread interrupted
INFO: Elapsed time: 88.631s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow
```
Changes in my WORKSPACE and BUILD are posted here:
```
diff --git a/tensorflow/BUILD b/tensorflow/BUILD
index 693a61c..67a3dd9 100644
--- a/tensorflow/BUILD
+++ b/tensorflow/BUILD
@@ -631,3 +631,11 @@ py_library(
     visibility = ["//visibility:public"],
     deps = ["//tensorflow/python:no_contrib"],
 )
+
+load("@com_grail_bazel_compdb//:aspects.bzl", "compilation_database")
+
+compilation_database(
+    name = "compdb",
+    targets = ["//tensorflow:libtensorflow_framework.so",
+               ],
+)


diff --git a/WORKSPACE b/WORKSPACE
index 7057d3f..d304e78 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -106,3 +106,8 @@ http_archive(
     ],
 )
 
+http_archive(
+    name = "com_grail_bazel_compdb",
+    strip_prefix = "bazel-compilation-database-0.4.5",
+    urls = ["https://github.com/grailbio/bazel-compilation-database/archive/0.4.5.tar.gz"],
+)
```
Could you please provide more detailed instruction on this, especially for TensorFlow ? @siddharthab

**Comment by siddharthab** [comment]
Sorry for the delay in getting to it.

The error message you provide seems like it could have been a network issue. To debug, you could look if the repo was fully fetched and that the aspects.bzl file was present there. You can do this by listing the files through `ls -l $(bazelisk info output_base)/external/com_grail_bazel_compdb/`.

I tried your changes, and it worked for me. The only difference is that I had to tweak the tensorflow target I was using as the one in your example is not the cc_binary target, but a generated file.

The part that I added to the BUILD file was:
```
load("@com_grail_bazel_compdb//:aspects.bzl", "compilation_database")

compilation_database(
    name = "compdb",
    targets = [
        "//tensorflow:libtensorflow_framework.so." + VERSION,
    ],
)
```

The stub added to the WORKSPACE file is the same as what you have.

I am going to close this issue. Please feel free to reopen.
