### ISSUE TITLE
swift support

### ISSUE THREAD

**Issue by joprice** [grailbio/bazel-compilation-database#71]
It seems that swift tooling can also consume clang compilation databases https://github.com/apple/sourcekit-lsp/blob/main/Sources/SKCore/CompilationDatabase.swift#L75. Could swift support be added?

**Comment by keith** [comment]
Definitely possible, we have some internal tooling for this use case and added support in SwiftLint for these files in some cases too

**Comment by siddharthab** [comment]
@keith I have given you write-access to the repository now. If you ever feel like adding major features or refactoring existing code, please go ahead and directly merge your changes.

I don't think I have done a good job at maintaining this project in the past year. In general, I am looking for new owners, or perhaps redirect to a better maintained fork.

**Comment by keith** [comment]
Thanks! I have to admit we're not using this in prod today, but I will try and find some time to contribute here!

**Comment by siddharthab** [comment]
This project is being archived.
