### ISSUE TITLE
Failed to generate

### ISSUE THREAD

**Issue by buaachendong** [grailbio/bazel-compilation-database#72]
ERROR: /home/chendong/.cache/bazel/_bazel_root/5f6cfd791ed6436cd7d0a9ad06515f99/external/bazel_compdb/aspects.bzl:386:17: unexpected tokens after kwarg
ERROR: /home/chendong/.cache/bazel/_bazel_root/5f6cfd791ed6436cd7d0a9ad06515f99/external/bazel_compdb/aspects.bzl:386:17: syntax error at ',': expected )
ERROR: Extension 'aspects.bzl' has errors

**Comment by slsyy** [comment]
Which version of the `bazel-compilation-database` and `bazel` do you use? Issue related to trailing commas after `kwargs` should be fixed in [this patch](https://github.com/bazelbuild/bazel/pull/8966/)

**Comment by buaachendong** [comment]
> Which version of the `bazel-compilation-database` and `bazel` do you use? Issue related to trailing commas after `kwargs` should be fixed in [this patch](https://github.com/bazelbuild/bazel/pull/8966/)

I use bazel 0.27.0 in a docker env.

**Comment by slsyy** [comment]
This change was delivered in the 0.29.0 https://github.com/bazelbuild/bazel/commit/a2dc9acd09382fa50d885a76c3977ebe6ba49bf1 , so you need to upgrade your bazel, or remove a trailing comma in https://github.com/grailbio/bazel-compilation-database/blob/aa58494efdf31c3e3525832b3d44d48bb3bc2b0b/aspects.bzl#L386

**Comment by siddharthab** [comment]
Thank you @slsyy. I will close this issue now.
