### ISSUE TITLE
unable to generate doesn't contain declared provider 'CompilationAspect'

### ISSUE THREAD

**Issue by shuzhang2016** [grailbio/bazel-compilation-database#77]
File "/home/xxx/.cache/bazel/_bazel_root/ac5062f7aad446d3e5ec57b2d49a6f5c/external/com_grail_bazel_compdb/aspects.bzl", line 343, in compilation_db.append
		target[CompilationAspect]
<merged target //:yyy> doesn't contain declared provider 'CompilationAspect'

**Comment by siddharthab** [comment]
Will it be possible to get a reproducible example? If not, then at least the release version of bazel-compilation-database and the bazel version you are using?

**Comment by siddharthab** [comment]
I think this will happen if one of the targets in the `targets` attribute of the `compilation_database` rule is not a supported `cc_*` or `objc_*` rule.

e2b2004 tries to remedy this a bit by making the aspect available for all types of rules. For unsupported rules, the aspect would just be empty.

I am going to close this now, but please feel free to reopen.
