### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by Barzi2001** [grailbio/bazel-compilation-database#80]
Hello!
I have noticed that when using this tool with cygwin you get errors like

generate.sh: line 111: workspace: C:/sw/bsw/compile_commands.json: No such file or directory

which seems that the script uses C: instead of /cygdrive/c
Would that be possible to fix so that one can use it also for Cygwin?

**Comment by siddharthab** [comment]
I don't have a Windows machine to test, but I think it should be resolved with ff7a98c. Please try now and let me know if it works.
