### ISSUE TITLE
Cannot generate compdb for targets that depend on `objc_library`

### ISSUE THREAD

**Issue by parbo** [grailbio/bazel-compilation-database#81]
I get this:

```
ERROR: <REDACTED>/BUILD.bazel:7:11: in @com_grail_bazel_compdb//:aspects.bzl%compilation_database_aspect aspect on objc_library rule <REDACTED>:os_objc_extra: 
Traceback (most recent call last):
	File "<REDACTED>/external/com_grail_bazel_compdb/aspects.bzl", line 279, column 44, in _compilation_database_aspect_impl
		compiler_info = _objc_compiler_info(ctx, target, srcs, feature_configuration, cc_toolchain)
	File "<REDACTED>/external/com_grail_bazel_compdb/aspects.bzl", line 214, column 61, in _objc_compiler_info
		defines = ["-D\"{}\"".format(val) for val in target.objc.define.to_list()]
Error: 'ObjcProvider' value has no field or method 'define'
```

I replaced some personal and company info with `<REDACTED>`.

Is this some known issue?

**Comment by PRESIDENT810** [comment]
Same problem using 0.4.0 version of release, but after I tried to clone the repository and use it instead of using the released version this problem no longer occurs. I guess they fixed this in a recent commit?

**Comment by keith** [comment]
What bazel version? I think probably at this point we can remove the objc provider usage because bazel uses ccinfo even for objc targets for compilation now

**Comment by PRESIDENT810** [comment]
ERROR: /Users/bytedance/github/examples/tutorial/ios-app/BUILD:3:13: in @bazel_compdb//:aspects.bzl%compilation_database_aspect aspect on objc_library rule //:UrlGetClasses:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_bytedance/dad233b544b1c15f2febf18120497cc8/external/bazel_compdb/aspects.bzl", line 270, column 44, in _compilation_database_aspect_impl
		compiler_info = _objc_compiler_info(ctx, target, srcs, feature_configuration, cc_toolchain)
	File "/private/var/tmp/_bazel_bytedance/dad233b544b1c15f2febf18120497cc8/external/bazel_compdb/aspects.bzl", line 203, column 13, in _objc_compiler_info
		defines = ["-D{}".format(val) for val in target.objc.define]
Error: type 'depset' is not iterable
ERROR: Analysis of aspect '@bazel_compdb//:aspects.bzl%compilation_database_aspect of //:UrlGetClasses' failed; build aborted: Analysis of target '//:UrlGetClasses' failed
INFO: Elapsed time: 1.503s
INFO: 0 processes.

The error I came across is something like this. The version of bazel-compdb is 0.4.0, and the bazel I use is a modified version inside company, which is based on bazel 3.7.2. After I changed to bazel-compdb 0.4.5 this error no longer occurs.

**Comment by keith** [comment]
Sounds like a separate issue, but either way it's fixed now?

**Comment by PRESIDENT810** [comment]
It seems so. I just tried 0.4.5 version and it works fine for me.

**Comment by siddharthab** [comment]
Thank you guys. I am going to close this issue now, but please feel free to let me know if there is something still remaining.
