### ISSUE TITLE
bazel External dependency header file not found

### ISSUE THREAD

**Issue by ims0** [grailbio/bazel-compilation-database#88]
The internal dependency header file can be found, but the external dependency header file cannot be found. It is estimated that there is a problem with the path processing

**Comment by ims0** [comment]
I checked the reason. It was missing to resolve the bazel dependency configuration, because the dependency library name needs to be changed to the library path. This mapping relationship is in the bazel configuration

**Comment by siddharthab** [comment]
It looks like you have an answer to your question. There is also more information in the README on how to automatically substitute OUTPUT_BASE with the correct value. Please feel free to reopen if it is not resolved.
