### ISSUE TITLE
bazel_compdb/aspects.bzl:329:19: name 'json' is not defined

### ISSUE THREAD

**Issue by lordrebel** [grailbio/bazel-compilation-database#95]
hey guys,

Im trying to using this repo to get compile_commands.json. Following the readme guide, I got the error:

 `bazel_compdb/aspects.bzl:329:19: name 'json' is not defined`

my command is:
`../bazel-compilation-database-0.5.2/generate.py -q //tensorflow/...`

my bazel version is: 
`bazel 3.7.2`

do you have any suggestions for me?

**Comment by siddharthab** [comment]
I think you need at least bazel 4.0. Versions before that do not have the JSON module.

**Comment by lordrebel** [comment]
yep, my bazel version is too low. 

I suggest you can add the  minimum requrie bazel version in readme.




many thx
