### ISSUE TITLE
Global repository compile_command.json

### ISSUE THREAD

**Issue by lromor** [grailbio/bazel-compilation-database#96]
Hi, 

if I wanted to embed the `generate.py` behavior as a bazel target in the repo (generate the aggregate compile_command.json for //...), how would you do it?

**Comment by siddharthab** [comment]
The typical way I have seen people calling bazel from inside bazel is if they use a different output_base setting for the bazel being called inside. It can be done but it's not so clean as you would think, and you may want to think what's the utility of wrapping a bazel command as a bazel target when the output is not being used by another bazel target.

**Comment by lromor** [comment]
I'm giving up, it's not very clean indeed. Thanks!
