### ISSUE TITLE
bazel-compilation-database generated compile_commands.json can only jump to declaration, definenation cannot

### ISSUE THREAD

**Issue by xiedeacc** [grailbio/bazel-compilation-database#99]
as title, bazel-compilation-database generated compile_commands.json can only jump to declaration, definenation cannot, youcompleteme auto complation works well, but cannot jump to defineation, only declaration, does this have any problem?

**Comment by siddharthab** [comment]
I think this could be a YouCompleteMe or libclang issue. The best way to check is if the commands inside the generated compile_commands.json look OK.

I am closing this issue now but please feel free to reopen with more information and a minimal repro if you can.
